// @generated by archmap 0.1.2 — vendored copy, do not edit
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { isAbsolute, join, relative, sep } from 'node:path';

// cm:why archmap never resolves Go imports itself. `go list` already knows the module graph,
//   build tags, replace directives and nested modules; reimplementing that resolution is the same
//   false-confidence trap the TypeScript provider avoids by shelling out to dependency-cruiser.
//   What `go list` does NOT report is which FILE holds which import — only per-package totals — so
//   this provider reads the import block itself and lets `go list` resolve every path.
// cm:edge contract -> src/graph/normalize.mjs — the shape returned here is the graph contract
// cm:edge lockstep -> src/install.mjs — MODULES lists every file the vendored copy gets. A provider
//   missing from that list makes `.forge/archmap/arch` crash on import, so the gate cannot run.
const TIMEOUT_MS = 180_000;

// One line per package: import path, dir, then the three file sets. A template beats `-json` here
// because the JSON form is a stream of concatenated objects with no delimiter to split on.
const LIST_FORMAT = [
  '{{.ImportPath}}',
  '{{.Dir}}',
  '{{join .GoFiles ","}}',
  '{{join .TestGoFiles ","}}',
  '{{join .XTestGoFiles ","}}',
].join('\t');

export function collect({ root, roots }) {
  // cm:guard a repo with no go.mod is Go's ABSENCE, not a failed gate — return an empty graph, never
  //   `ok: false`. A provider that reports failure for a language the repo does not use prints a
  //   scary line on every run of every other language, and a gate nobody reads is not a gate.
  if (!existsSync(join(root, 'go.mod'))) {
    return { ok: true, language: 'go', provider: 'absent', files: [], edges: [], unresolvable: [] };
  }

  const res = spawnSync('go', ['list', '-f', LIST_FORMAT, './...'], {
    cwd: root,
    encoding: 'utf8',
    timeout: TIMEOUT_MS,
    maxBuffer: 64 * 1024 * 1024,
  });

  // cm:guard go.mod exists but `go list` could not run: that is exit-2 territory, so it MUST be
  //   `ok: false`. Returning an empty graph here would let every contract pass on a Go repo whose
  //   toolchain is missing — the check would be loudest exactly when it knows least.
  if (res.status !== 0 || !res.stdout.trim()) {
    const why = (res.stderr || res.error?.message || `exit ${res.status}`).trim().split('\n')[0];
    return { ok: false, reason: `go list failed: ${why}` };
  }

  const packages = parseList(res.stdout, root);
  const scope = normaliseRoots(roots);

  const files = [];
  const edges = [];
  const unresolvable = [];

  for (const pkg of packages.values()) {
    for (const file of pkg.files) {
      if (!inScope(file, scope)) continue;
      files.push(file);

      let text;
      try {
        text = readFileSync(join(root, file), 'utf8');
      } catch {
        unresolvable.push({ from: file, spec: file, why: 'unreadable' });
        continue;
      }

      for (const spec of importsOf(text)) {
        const target = packages.get(spec);
        // An import that `go list` never named is either the standard library or a dependency
        // outside this module: resolved, but with no file in this repo to attribute an edge to.
        if (!target) continue;
        if (target.entry === null) {
          unresolvable.push({ from: file, spec, why: 'package has no non-test Go file' });
          continue;
        }
        if (target.entry === file) continue;
        edges.push({ from: file, to: target.entry, dynamic: false });
      }
    }
  }

  return { ok: true, language: 'go', provider: 'go list', files, edges, unresolvable };
}

function parseList(stdout, root) {
  const packages = new Map();
  for (const line of stdout.split('\n')) {
    if (!line.trim()) continue;
    const [importPath, dir, goFiles, testFiles, xTestFiles] = line.split('\t');
    if (!importPath || !dir) continue;

    const rel = (name) => toPosix(relative(root, isAbsolute(dir) ? join(dir, name) : join(root, dir, name)));
    const own = split(goFiles).map(rel);
    const all = [...own, ...split(testFiles).map(rel), ...split(xTestFiles).map(rel)];

    // cm:why the edge target is the package's first non-test file, chosen by sort so it is stable
    //   across machines. Go imports a PACKAGE, not a file, and the mapper assigns modules by path
    //   glob — so any file in the directory maps to the same module and the module-level verdict is
    //   identical. Emitting one edge per file in the imported package would multiply a single
    //   logical violation into one finding per file in the target.
    packages.set(importPath, { entry: own.length ? [...own].sort()[0] : null, files: all });
  }
  return packages;
}

function split(csv) {
  return csv ? csv.split(',').filter(Boolean) : [];
}

function toPosix(p) {
  return sep === '/' ? p : p.split(sep).join('/');
}

function normaliseRoots(roots) {
  const cleaned = (roots ?? ['.'])
    .map((r) => toPosix(r).replace(/^\.\//, '').replace(/\/+$/, ''))
    .filter((r) => r !== '' && r !== '.');
  return cleaned.length ? cleaned : null;
}

function inScope(file, scope) {
  return scope === null || scope.some((r) => file === r || file.startsWith(`${r}/`));
}

/**
 * Import paths declared in one Go source file.
 *
 * Exact rather than best-effort in two steps: comments are removed by a scanner that knows string
 * and rune literals, then the text is cut at the first top-level declaration. The cut is safe
 * because the language REQUIRES every import declaration to precede every other declaration — so
 * nothing but the package clause, imports and comments can appear before it, and no string literal
 * from the body can be mistaken for an import.
 */
export function importsOf(text) {
  const head = cutAtFirstDeclaration(stripComments(text));
  const specs = [];

  for (const group of head.matchAll(/\bimport\s*\(([\s\S]*?)\)/g)) {
    for (const lit of group[1].matchAll(/"([^"\n]*)"|`([^`]*)`/g)) {
      specs.push(lit[1] ?? lit[2]);
    }
  }
  for (const single of head.matchAll(/\bimport\s+(?:[A-Za-z_.][\w.]*\s+)?(?:"([^"\n]*)"|`([^`]*)`)/g)) {
    specs.push(single[1] ?? single[2]);
  }

  return [...new Set(specs.filter(Boolean))];
}

function cutAtFirstDeclaration(text) {
  const at = text.search(/^[ \t]*(?:func|type|var|const)\b/m);
  return at === -1 ? text : text.slice(0, at);
}

function stripComments(text) {
  let out = '';
  let i = 0;
  while (i < text.length) {
    const c = text[i];
    const next = text[i + 1];

    if (c === '/' && next === '/') {
      while (i < text.length && text[i] !== '\n') i++;
      continue;
    }
    if (c === '/' && next === '*') {
      i += 2;
      // A block comment spanning lines acts as a newline, which keeps the line-anchored cut honest.
      let sawNewline = false;
      while (i < text.length && !(text[i] === '*' && text[i + 1] === '/')) {
        if (text[i] === '\n') sawNewline = true;
        i++;
      }
      i += 2;
      out += sawNewline ? '\n' : ' ';
      continue;
    }
    if (c === '"' || c === '`' || c === "'") {
      const quote = c;
      out += c;
      i++;
      while (i < text.length) {
        if (quote !== '`' && text[i] === '\\') {
          out += text.slice(i, i + 2);
          i += 2;
          continue;
        }
        out += text[i];
        if (text[i] === quote) {
          i++;
          break;
        }
        i++;
      }
      continue;
    }

    out += c;
    i++;
  }
  return out;
}
