// @generated by archmap 0.1.2 — vendored copy, do not edit
import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

// cm:why archmap never resolves TypeScript itself. tsconfig paths, pnpm symlinks, barrel re-exports
//   and `import type` erasure are an endless edge-case surface that dependency-cruiser already
//   handles; reimplementing it would move the false-confidence problem one layer deeper rather
//   than removing it. This provider only normalises its output.
// cm:edge contract -> src/graph/normalize.mjs — the shape returned here is the graph contract
const TIMEOUT_MS = 180_000;

const BIN_REL = join('node_modules', 'dependency-cruiser', 'bin', 'dependency-cruise.mjs');

// cm:why resolved by walking node_modules, not require.resolve: dependency-cruiser's exports map
//   blocks every subpath including package.json, and a bin was never part of that contract anyway
function walkUpFor(start, label) {
  for (let dir = start; ; dir = dirname(dir)) {
    const candidate = join(dir, BIN_REL);
    if (existsSync(candidate)) return { bin: candidate, from: label };
    if (dirname(dir) === dir) return null;
  }
}

/**
 * Resolves dependency-cruiser from the TARGET repo first, then from archmap's own install.
 * A project pinned to its own version must get that version's verdicts, not ours.
 */
function resolveCruiser(root) {
  return walkUpFor(root, 'project')
    ?? walkUpFor(dirname(fileURLToPath(import.meta.url)), 'archmap');
}

// cm:why dependency-cruiser's --exclude is a REGEX and it refuses patterns it judges pathological,
//   so only whole-directory excludes are pushed down to it as a cheap segment alternation. Every
//   other glob is applied by the mapper instead, which is why an exclude never silently widens scope.
// cm:edge protocol -> src/graph/map.mjs — the excludes not passed here are enforced by buildMapper
function dirExcludeRe(globs) {
  const segments = new Set();
  for (const g of globs) {
    const m = /^\*\*\/([^/*{}]+)\/\*\*$/.exec(g);
    if (m) segments.add(m[1].replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  }
  return segments.size ? `(^|/)(${[...segments].join('|')})(/|$)` : null;
}

export function collect({ root, roots, exclude }) {
  const cruiser = resolveCruiser(root);
  if (!cruiser) {
    // cm:guard no package.json means this repo is not a JS/TS project, so the resolver's absence is
    //   the LANGUAGE's absence — return an empty graph. A Go-only repo must not be told on every
    //   single run that a TypeScript dependency is missing; noise on a gate is how a gate stops
    //   being read. With a package.json present the resolver IS required, and this stays `ok: false`
    //   so an unrunnable gate never reports clean.
    if (!existsSync(join(root, 'package.json'))) {
      return { ok: true, language: 'ts', provider: 'absent', files: [], edges: [], unresolvable: [] };
    }
    return { ok: false, reason: 'dependency-cruiser is not installed in this project or in archmap' };
  }

  const args = [
    cruiser.bin,
    ...roots,
    '--output-type', 'json',
    '--no-config',
    '--ts-pre-compilation-deps',
    '--do-not-follow', 'node_modules',
  ];
  const skip = dirExcludeRe(exclude);
  if (skip) args.push('--exclude', skip);

  // cm:guard `--no-config` also drops the tsconfig, so without this every `paths` alias lands in
  //   `unresolvable` and the graph goes VACUOUS — contracts then pass because the edges are absent,
  //   not because the code obeys them. Measured on a Next.js app that imports through `@/`:
  //   2565 unresolvable vs 3219 resolved edges, 2 files in the whole fan-out distribution.
  const tsconfig = ['tsconfig.json', 'jsconfig.json'].map((f) => join(root, f)).find(existsSync);
  if (tsconfig) args.push('--ts-config', tsconfig);

  const res = spawnSync(process.execPath, args, {
    cwd: root,
    encoding: 'utf8',
    timeout: TIMEOUT_MS,
    maxBuffer: 256 * 1024 * 1024,
  });

  // cm:guard dependency-cruiser exits non-zero when it REPORTS violations, which is not a failure
  //   to run — only an unparseable stdout is. Treating exit code as failure here silently drops
  //   the whole graph and every contract then passes.
  if (!res.stdout) {
    const why = (res.stderr || res.error?.message || `exit ${res.status}`).trim().split('\n')[0];
    return { ok: false, reason: `dependency-cruiser produced no output: ${why}` };
  }

  let report;
  try {
    report = JSON.parse(res.stdout);
  } catch {
    return { ok: false, reason: 'dependency-cruiser output was not valid JSON' };
  }

  const edges = [];
  const files = new Set();
  const unresolvable = [];

  for (const mod of report.modules ?? []) {
    if (mod.coreModule || mod.couldNotResolve) continue;
    files.add(mod.source);
    for (const dep of mod.dependencies ?? []) {
      if (dep.coreModule) continue;
      if (dep.couldNotResolve) {
        unresolvable.push({ from: mod.source, spec: dep.module, why: 'could not resolve' });
        continue;
      }
      if (dep.dynamic && !dep.resolved) {
        unresolvable.push({ from: mod.source, spec: dep.module, why: 'dynamic import' });
        continue;
      }
      edges.push({ from: mod.source, to: dep.resolved, dynamic: Boolean(dep.dynamic) });
    }
  }

  return { ok: true, language: 'ts', provider: cruiser.from, files: [...files], edges, unresolvable };
}
