// @generated by archmap 0.1.2 — vendored copy, do not edit
import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadManifest, findRoot, ManifestError, BASELINE_NAME } from './manifest.mjs';
import { normalize } from './graph/normalize.mjs';
import { evaluate } from './contracts/index.mjs';
import { install, doctor, VENDOR_DIR } from './install.mjs';
import * as ts from './providers/ts.mjs';
import * as go from './providers/go.mjs';

// cm:edge lockstep -> src/install.mjs — every provider here must also be in MODULES, or the
//   vendored copy crashes on import and the gate cannot run at all.
const PROVIDERS = { ts, go };

// cm:guard excluded unconditionally, never through the manifest's own `exclude` — a repo onboarded
//   by an older release carries that list frozen in its file, and would then scan the vendored copy
const VENDOR_GLOB = `**/${VENDOR_DIR.split('/').join('/')}/**`;

const USAGE = `arch — architecture conformance from a declared manifest

  arch check [paths...]     check the repo against .arch.json
    --json                  machine-readable output
    --stats                 graph and coverage numbers only, no verdict
    --strict-unresolvable   count unresolvable edges toward the exit code

  arch install              vendor arch into ${VENDOR_DIR}/ so CI and contributors
                            without a global install are held to the same copy
    --force                 overwrite an existing vendored copy

  arch doctor               what this repo has committed vs what is running now

Exit: 0 clean · 1 violations · 2 the gate could not run
`;

// cm:guard exit 2 means the gate could not run and is never interchangeable with 1. Every
//   fail-open bug in tools of this kind has the same shape: a broken invocation produces an
//   empty scope and a green summary.
const E_OK = 0;
const E_VIOLATION = 1;
const E_CANNOT_RUN = 2;

function die(msg) {
  process.stderr.write(`arch: ${msg}\n`);
  process.exit(E_CANNOT_RUN);
}

function loadBaseline(root) {
  const path = join(root, BASELINE_NAME);
  if (!existsSync(path)) return { entries: new Set(), present: false };
  try {
    const raw = JSON.parse(readFileSync(path, 'utf8'));
    return { entries: new Set(raw.frozen ?? []), present: true };
  } catch {
    return { entries: new Set(), present: false, unreadable: true };
  }
}

// cm:why the baseline key is the normalised EDGE, never file:line or a text hash — renaming a file,
//   moving code and reformatting must all be free. A line-keyed baseline unfreezes wholesale on
//   the first reflow, which is the failure this key shape exists to avoid.
export function baselineKey(f) {
  return `${f.contract}|${f.edge}`;
}

function collectGraph(manifest, roots) {
  const exclude = [...manifest.exclude, ...manifest.generated.globs];
  const results = [];
  const failures = [];
  for (const [lang, provider] of Object.entries(PROVIDERS)) {
    const r = provider.collect({ root: manifest.root, roots, exclude });
    if (!r.ok) failures.push(`${lang}: ${r.reason}`);
    else results.push(r);
  }
  return { results, failures };
}

function render(report, opts) {
  const out = [];
  const { coverage, graph } = report;

  out.push(
    `archmap · ${coverage.total} files · ${graph.edgeCount} edges · ${report.contractCount} contracts`,
  );
  out.push(
    `  mapped ${coverage.mappedPct}%  (source ${coverage.source} · test ${coverage.test} · unmapped ${coverage.unmapped} · generated ${coverage.generated})`,
  );
  if (report.unresolvable.length) {
    out.push(`  ${report.unresolvable.length} unresolvable edges — not counted as violations`);
  }
  for (const s of report.skipped) out.push(`  contract "${s.id}" skipped: ${s.why}`);

  if (opts.stats) {
    out.push('', 'fan-out distribution (files by distinct modules reached):');
    for (const [n, count] of report.fanOut) out.push(`  ${String(n).padStart(3)} modules  ${count} files`);
    return out.join('\n');
  }

  const shown = report.blocking.concat(report.advisory);
  if (shown.length) {
    out.push('');
    for (const f of shown) {
      const tag = f.status === 'locked' ? 'error' : 'warn';
      out.push(`${f.from}${f.to ? ` -> ${f.to}` : ''}`);
      out.push(`  ${tag}  [${f.contract}] ${f.message}`);
    }
    const kinds = new Set(shown.map((f) => f.type));
    out.push('');
    for (const k of kinds) out.push(`${k}: ${report.remedies[k]}`);
    out.push(report.policy);
  }

  out.push('');
  out.push(
    `${report.blocking.length} blocking · ${report.advisory.length} advisory · ${report.frozen} frozen by baseline`,
  );
  return out.join('\n');
}

export function main(argv) {
  const args = argv.slice(2);
  if (args.includes('--help') || args[0] === 'help') {
    process.stdout.write(USAGE);
    return E_OK;
  }
  const cmd = args[0] ?? 'check';
  if (!['check', 'install', 'doctor'].includes(cmd)) die(`unknown command "${cmd}"`);

  const flags = new Set(args.filter((a) => a.startsWith('--')));
  const paths = args.slice(1).filter((a) => !a.startsWith('--'));

  const root = findRoot();
  if (!root) die('no .arch.json here or in any parent directory');

  if (cmd === 'install') return doInstall(root, flags);
  if (cmd === 'doctor') return doDoctor(root);

  let manifest;
  try {
    manifest = loadManifest(root);
  } catch (e) {
    if (e instanceof ManifestError) die(e.message);
    throw e;
  }
  manifest.exclude = [VENDOR_GLOB, ...manifest.exclude];

  const roots = paths.length ? paths : ['.'];
  const { results, failures } = collectGraph(manifest, roots);
  if (results.length === 0) die(failures.join('; ') || 'no provider produced a graph');

  const graph = normalize(manifest, results);
  if (graph.files.size === 0) die(`scope matched no files (${roots.join(', ')})`);

  const { findings, skipped } = evaluate(manifest, graph);
  const baseline = loadBaseline(root);

  const fresh = [];
  let frozen = 0;
  for (const f of findings) {
    if (baseline.entries.has(baselineKey(f))) { frozen++; continue; }
    fresh.push(f);
  }

  const blocking = fresh.filter((f) => f.status === 'locked');
  const advisory = fresh.filter((f) => f.status !== 'locked');

  const fanOut = tallyFanOut(graph);
  const report = {
    ok: blocking.length === 0,
    coverage: graph.coverage,
    graph: { edgeCount: graph.edges.length },
    contractCount: manifest.contracts.length,
    unresolvable: graph.unresolvable,
    skipped,
    blocking,
    advisory,
    frozen,
    fanOut,
    remedies: Object.fromEntries(fresh.map((f) => [f.type, f.remedy])),
    policy: fresh[0]?.policy ?? '',
    providerFailures: failures,
  };

  process.stdout.write(
    flags.has('--json') ? `${JSON.stringify(report, null, 2)}\n` : `${render(report, { stats: flags.has('--stats') })}\n`,
  );

  if (flags.has('--stats')) return E_OK;
  if (flags.has('--strict-unresolvable') && graph.unresolvable.length > 0) return E_VIOLATION;
  return blocking.length > 0 ? E_VIOLATION : E_OK;
}

function doDoctor(root) {
  const d = doctor(root);
  const out = [`archmap doctor · ${root}`];
  out.push(`  running now        ${d.running}  (${d.from})`);
  out.push(`  vendored checker   ${d.vendored ?? `absent — run: arch install`}`);
  for (const p of d.peers) {
    out.push(`  ${p.pkg.padEnd(18)} ${p.found ? 'found' : `MISSING — ${p.why} cannot run`}`);
  }

  // cm:guard skew is the whole point of this verb: CI runs the vendored copy, so a stale one keeps
  //   passing while the source has moved. Report it as a failure, never as a note.
  const skewed = d.vendored !== null && !d.vendored.startsWith(d.running) && d.running !== d.vendored;
  if (skewed) {
    out.push('');
    out.push(`  SKEW — the repo is pinned to ${d.vendored}, you are running ${d.running}.`);
    out.push('  CI uses the vendored copy, so anything you check here can disagree with the gate.');
    out.push('  Re-vendor and commit the result: arch install --force');
  }
  const missing = d.peers.some((p) => !p.found);
  process.stdout.write(`${out.join('\n')}\n`);
  return skewed || missing ? E_VIOLATION : E_OK;
}

function doInstall(root, flags) {
  const r = install(root, { force: flags.has('--force') });
  if (r.already) {
    process.stdout.write(`arch install: ${VENDOR_DIR} already at ${r.already} — pass --force to rewrite\n`);
  } else {
    process.stdout.write(`arch install: vendored ${r.files.length} files into ${VENDOR_DIR}\n`);
    for (const f of r.files) process.stdout.write(`  ${f}\n`);
    process.stdout.write('Commit that directory: it is what holds CI and a contributor without a\n');
    process.stdout.write('global install to the same copy, and pins the repo to a reviewed version.\n');
  }

  // cm:guard a missing peer must be reported HERE, not discovered as an empty graph in CI — the
  //   vendored copy has no node_modules of its own, so the resolver has to come from the project
  const missing = r.peers.filter((p) => !p.found);
  if (missing.length > 0) {
    process.stdout.write('\nStill needed in this project:\n');
    for (const p of missing) process.stdout.write(`  ${p.pkg} — ${p.why}\n`);
    return E_VIOLATION;
  }
  return E_OK;
}

function tallyFanOut(graph) {
  const reach = new Map();
  for (const e of graph.edges) {
    if (!e.toModule || e.fromModule === e.toModule) continue;
    if (!reach.has(e.fromFile)) reach.set(e.fromFile, new Set());
    reach.get(e.fromFile).add(e.toModule);
  }
  const hist = new Map();
  for (const mods of reach.values()) hist.set(mods.size, (hist.get(mods.size) ?? 0) + 1);
  return [...hist.entries()].sort((a, b) => a[0] - b[0]);
}
