// @generated by archmap 0.1.2 — vendored copy, do not edit
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

export const VENDOR_DIR = join('.forge', 'archmap');

// cm:guard this list IS the vendored surface — a module added to src/ and left out here makes the
//   committed copy crash on import, and only in the consuming repo where nobody is watching
const MODULES = [
  'cli.mjs',
  'install.mjs',
  'index.mjs',
  'manifest.mjs',
  join('graph', 'map.mjs'),
  join('graph', 'normalize.mjs'),
  join('contracts', 'index.mjs'),
  join('providers', 'ts.mjs'),
  join('providers', 'go.mjs'),
];

const SHIM = `#!/bin/sh
# Vendored archmap. Resolves its own real location so the repo's copy wins over any
# arch on PATH — the same precedence the CI job and the editor hook both rely on.
d=$(dirname "$(readlink -f "$0")")
exec node "$d/entry.mjs" "$@"
`;

// cm:guard the shim must exec an entry that CALLS main, never src/cli.mjs itself — cli.mjs only
//   exports it, so running the module directly prints nothing and exits 0: a silent fail-open that
//   reads as a clean repo. Verified once by shipping it (a 0.06s "pass" on a 5s scan).
const ENTRY = `#!/usr/bin/env node
import { main } from './src/cli.mjs';

process.exitCode = main(process.argv);
`;

// cm:guard the vendored copy MUST carry a @generated marker. archmap's own source is annotated, and
//   those cm:edge targets are relative to archmap's repo — unmarked, a consuming repo's codemap
//   scans them and reports CM102 dangling edges against paths that were never meant to exist there.
// cm:edge contract -> src/providers/ts.mjs — the annotations being escaped are in that file
function stamp(text) {
  const marker = `// @generated by archmap ${version()} — vendored copy, do not edit\n`;
  return text.startsWith('#!') 
    ? text.replace(/^(#![^\n]*\n)/, `$1${marker}`)
    : marker + text;
}

function root() {
  return join(dirname(fileURLToPath(import.meta.url)), '..');
}

// cm:guard the vendored copy has no package.json — it ships a VERSION stamp instead. Reading only
//   package.json makes every verb crash there, and the crash surfaces in the consuming repo where
//   nobody is watching. Verified once by shipping it: `arch install` from .forge/archmap threw ENOENT.
export function version() {
  for (const [file, read] of [
    ['package.json', (t) => JSON.parse(t).version],
    ['VERSION', (t) => t.trim()],
  ]) {
    const path = join(root(), file);
    if (existsSync(path)) return read(readFileSync(path, 'utf8'));
  }
  return 'unknown';
}

/** Whether this copy is the vendored one, which has a VERSION stamp and no package.json. */
export function isVendored() {
  return !existsSync(join(root(), 'package.json')) && existsSync(join(root(), 'VERSION'));
}

/**
 * What the repo has committed versus what is running now. Skew is silent otherwise: editing the
 * source leaves the vendored copy stale, and CI keeps passing on the stale one.
 */
export function doctor(target) {
  const stamp = join(target, VENDOR_DIR, 'VERSION');
  return {
    running: version(),
    vendored: existsSync(stamp) ? readFileSync(stamp, 'utf8').trim() : null,
    from: isVendored() ? 'the repo\'s vendored copy' : 'a source checkout',
    peers: peerStatus(target),
  };
}

/**
 * Providers shell out to a resolver the CONSUMING repo must own, because a project pinned to its
 * own version has to get that version's graph. The vendored copy has no node_modules of its own,
 * so a missing peer is reported here rather than discovered as an empty graph in CI.
 */
export function peerStatus(target) {
  const out = [];
  // cm:guard a peer is only "still needed" when its LANGUAGE is here. Telling a Go-only repo that a
  //   TypeScript resolver is missing sends someone to install a dependency the project will never
  //   use, and teaches them that this tool's warnings are noise.
  // cm:edge contract -> src/providers/ts.mjs — same absence test as the provider's, and it must stay
  //   the same one: a peer reported missing where the provider self-skips is a contradiction.
  const languages = [
    ['dependency-cruiser', 'the TypeScript/JavaScript provider', existsSync(join(target, 'package.json'))],
  ];
  for (const [pkg, why, present] of languages) {
    if (!present) continue;
    let found = false;
    try {
      createRequire(join(target, 'package.json')).resolve(`${pkg}/package.json`);
      found = true;
    } catch {
      found = existsSync(join(target, 'node_modules', pkg));
    }
    out.push({ pkg, why, found });
  }
  return out;
}

export function install(target, { force = false } = {}) {
  const dir = join(target, VENDOR_DIR);
  if (existsSync(dir) && !force) {
    const stamp = join(dir, 'VERSION');
    const have = existsSync(stamp) ? readFileSync(stamp, 'utf8').trim() : 'unknown';
    if (have === version()) return { dir, files: [], already: have, peers: peerStatus(target) };
  }

  const src = join(root(), 'src');
  const files = [];
  for (const rel of MODULES) {
    const to = join(dir, 'src', rel);
    mkdirSync(dirname(to), { recursive: true });
    writeFileSync(to, stamp(readFileSync(join(src, rel), 'utf8')));
    files.push(join(VENDOR_DIR, 'src', rel));
  }

  mkdirSync(join(dir, 'schema'), { recursive: true });
  copyFileSync(join(root(), 'schema', 'arch.schema.json'), join(dir, 'schema', 'arch.schema.json'));
  files.push(join(VENDOR_DIR, 'schema', 'arch.schema.json'));

  copyFileSync(join(root(), 'SPEC.md'), join(dir, 'SPEC.md'));
  files.push(join(VENDOR_DIR, 'SPEC.md'));

  const entry = join(dir, 'entry.mjs');
  writeFileSync(entry, ENTRY);
  files.push(join(VENDOR_DIR, 'entry.mjs'));

  const shim = join(dir, 'arch');
  writeFileSync(shim, SHIM);
  chmodSync(shim, 0o755);
  files.push(join(VENDOR_DIR, 'arch'));

  writeFileSync(join(dir, 'VERSION'), `${version()}\n`);
  files.push(join(VENDOR_DIR, 'VERSION'));

  return { dir, files, already: null, peers: peerStatus(target) };
}
