// @generated by archmap 0.1.2 — vendored copy, do not edit
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';

export const MANIFEST_NAME = '.arch.json';
export const BASELINE_NAME = '.arch.baseline.json';

// cm:why JSON, not YAML: the vendored copy must parse with zero dependencies, and a hand-rolled
//   YAML subset is a silent-failure surface in the one file that defines what "correct" means.
//   Comments live in each contract's `description`, which the report can print as part of the remedy.
export const CONTRACT_TYPES = [
  'layers',
  'forbidden',
  'independence',
  'boundary',
  'fan-out',
  'cardinality',
  'interface-only',
  'absence',
];

// cm:guard every type here must have an evaluator registered in src/contracts/index.mjs, or a
//   manifest naming it validates clean and is then silently never checked
export const GRAPH_TYPES = new Set(['layers', 'forbidden', 'independence', 'boundary', 'fan-out']);

export const STATUSES = ['draft', 'locked'];

export function findRoot(from = process.cwd()) {
  for (let dir = from; ; dir = dirname(dir)) {
    if (existsSync(join(dir, MANIFEST_NAME))) return dir;
    if (dirname(dir) === dir) return null;
  }
}

class ManifestError extends Error {}

function fail(msg) {
  throw new ManifestError(msg);
}

function asArray(value, field) {
  if (value === undefined) return [];
  if (!Array.isArray(value)) fail(`${field} must be an array`);
  return value;
}

/**
 * Reads and validates the manifest. Throws ManifestError with a message naming the offending
 * field; the CLI turns that into exit 2, because a manifest it cannot read is a gate that
 * cannot run rather than a codebase that failed.
 */
export function loadManifest(root) {
  const path = join(root, MANIFEST_NAME);
  if (!existsSync(path)) fail(`no ${MANIFEST_NAME} at ${root}`);

  let raw;
  try {
    raw = JSON.parse(readFileSync(path, 'utf8'));
  } catch (e) {
    fail(`${MANIFEST_NAME} is not valid JSON: ${e.message}`);
  }

  if (raw.version !== 1) fail(`version must be 1, got ${JSON.stringify(raw.version)}`);

  const modules = raw.modules ?? {};
  if (typeof modules !== 'object' || Array.isArray(modules)) fail('modules must be an object');
  for (const [name, globs] of Object.entries(modules)) {
    if (!Array.isArray(globs) || globs.some((g) => typeof g !== 'string')) {
      fail(`modules.${name} must be an array of glob strings`);
    }
  }

  const contracts = asArray(raw.contracts, 'contracts').map((c, i) => validateContract(c, i, modules));
  const ids = new Set();
  for (const c of contracts) {
    if (ids.has(c.id)) fail(`duplicate contract id "${c.id}"`);
    ids.add(c.id);
  }

  return {
    root,
    version: 1,
    modules,
    tests: {
      globs: asArray(raw.tests?.globs, 'tests.globs'),
      relax: asArray(raw.tests?.relax, 'tests.relax'),
    },
    generated: { globs: asArray(raw.generated?.globs, 'generated.globs') },
    exclude: asArray(raw.exclude, 'exclude'),
    size: raw.size ?? null,
    contracts,
  };
}

function validateContract(c, i, modules) {
  const where = c?.id ? `contract "${c.id}"` : `contracts[${i}]`;
  if (!c || typeof c !== 'object') fail(`${where} must be an object`);
  if (typeof c.id !== 'string' || !/^[a-z0-9][a-z0-9-]*$/.test(c.id)) {
    fail(`${where} needs a kebab-case id`);
  }
  if (!CONTRACT_TYPES.includes(c.type)) {
    fail(`${where}: unknown type "${c.type}" — one of: ${CONTRACT_TYPES.join(', ')}`);
  }
  const status = c.status ?? 'draft';
  if (!STATUSES.includes(status)) fail(`${where}: status must be draft or locked`);

  const known = (name) => {
    if (name !== '*' && !(name in modules)) fail(`${where} names unknown module "${name}"`);
  };

  switch (c.type) {
    case 'layers': {
      const order = asArray(c.order, `${where}.order`);
      if (order.length < 2) fail(`${where}: layers needs at least two entries in order`);
      order.forEach(known);
      break;
    }
    case 'forbidden': {
      if (typeof c.from !== 'string') fail(`${where}: forbidden needs "from"`);
      known(c.from);
      const to = typeof c.to === 'string' ? [c.to] : asArray(c.to, `${where}.to`);
      if (to.length === 0) fail(`${where}: forbidden needs "to"`);
      to.forEach((t) => {
        if (!t.includes('/') && !t.includes('*')) known(t);
      });
      break;
    }
    case 'independence': {
      const mods = asArray(c.modules, `${where}.modules`);
      if (mods.length < 2) fail(`${where}: independence needs at least two modules`);
      mods.forEach(known);
      break;
    }
    case 'boundary': {
      if (typeof c.module !== 'string') fail(`${where}: boundary needs "module"`);
      known(c.module);
      if (asArray(c.public, `${where}.public`).length === 0) {
        fail(`${where}: boundary needs a non-empty "public"`);
      }
      break;
    }
    case 'fan-out': {
      if (!Number.isInteger(c.max_modules) || c.max_modules < 1) {
        fail(`${where}: fan-out needs a positive integer "max_modules"`);
      }
      if (c.scope && !['file', 'module'].includes(c.scope)) {
        fail(`${where}: fan-out scope must be file or module`);
      }
      break;
    }
    default:
      break;
  }

  return { ...c, status, scope: c.scope ?? 'file' };
}

export { ManifestError };
