// @generated by archmap 0.1.2 — vendored copy, do not edit
import { matchesAny } from '../graph/map.mjs';
import { moduleClosure, witness } from '../graph/normalize.mjs';

const REMEDY = {
  layers:
    'Higher layers may depend on lower ones, never the reverse. Invert the call, or move the shared type down into the lower layer.',
  forbidden:
    'Declare an interface in the depending module and implement it on the other side, or move the shared code into a module both may depend on.',
  independence:
    'Two features share code only through a module both may depend on. Extract the shared contract there — do not reach across.',
  boundary:
    'Import the module through its declared entry point. If what you need is not exported there, export it — do not reach past the surface.',
  'fan-out':
    'This file coordinates too many modules. Split it by responsibility, or push the coordination up into the layer that owns the use case.',
};

const POLICY = 'Fix the source, not the check: do not widen .arch.json to make this pass.';

function finding(contract, parts) {
  return {
    contract: contract.id,
    type: contract.type,
    status: contract.status,
    remedy: REMEDY[contract.type],
    policy: POLICY,
    ...parts,
  };
}

// cm:guard `relax` only ever removes a contract type from test files. Widening it to source files
//   turns the test glob into a general exemption list, which is the escape route this design
//   exists to close.
function relaxed(manifest, contract, edge) {
  return edge.fromKind === 'test' && manifest.tests.relax.includes(contract.type);
}

function layers(contract, graph, manifest) {
  const rank = new Map(contract.order.map((m, i) => [m, i]));
  const out = [];
  for (const e of graph.edges) {
    if (!rank.has(e.fromModule) || !rank.has(e.toModule)) continue;
    if (e.fromModule === e.toModule) continue;
    if (relaxed(manifest, contract, e)) continue;
    if (rank.get(e.fromModule) > rank.get(e.toModule)) {
      out.push(finding(contract, {
        from: e.fromFile,
        to: e.toFile,
        message: `${e.fromModule} sits below ${e.toModule} and must not depend on it`,
        edge: `${e.fromModule} -> ${e.toModule}`,
      }));
    }
  }
  return out;
}

function forbidden(contract, graph, manifest) {
  const targets = typeof contract.to === 'string' ? [contract.to] : contract.to;
  const wildcard = targets.includes('*');
  const named = new Set(targets.filter((t) => t !== '*' && !t.includes('/') && !t.includes('*')));
  const globs = targets.filter((t) => t !== '*' && (t.includes('/') || t.includes('*')));
  const out = [];

  for (const e of graph.edges) {
    if (e.fromModule !== contract.from) continue;
    if (e.toModule === contract.from) continue;
    if (relaxed(manifest, contract, e)) continue;

    const hit = wildcard
      || (e.toModule !== null && named.has(e.toModule))
      || (globs.length > 0 && matchesAny(e.toFile, globs));
    if (!hit) continue;

    out.push(finding(contract, {
      from: e.fromFile,
      to: e.toFile,
      message: wildcard
        ? `${contract.from} must not depend on anything outside itself`
        : `${contract.from} must not depend on ${e.toModule ?? e.toFile}`,
      edge: `${e.fromModule} -> ${e.toModule ?? e.toFile}`,
    }));
  }
  return out;
}

function independence(contract, graph, manifest) {
  const { direct, closure } = moduleClosure(graph);
  const set = new Set(contract.modules);
  const out = [];

  for (const a of contract.modules) {
    for (const b of closure.get(a) ?? []) {
      if (a === b || !set.has(b)) continue;
      const path = witness(direct, a, b) ?? [a, b];
      const hop = firstEdge(graph, a, path[1] ?? b, manifest, contract);
      if (!hop) continue;
      out.push(finding(contract, {
        from: hop.fromFile,
        to: hop.toFile,
        message: path.length > 2
          ? `${a} reaches ${b} through ${path.slice(1, -1).join(' -> ')}`
          : `${a} must not depend on ${b}`,
        edge: path.join(' -> '),
      }));
    }
  }
  return out;
}

function firstEdge(graph, from, to, manifest, contract) {
  for (const e of graph.edges) {
    if (e.fromModule === from && e.toModule === to && !relaxed(manifest, contract, e)) return e;
  }
  return null;
}

function boundary(contract, graph, manifest) {
  const out = [];
  for (const e of graph.edges) {
    if (e.toModule !== contract.module) continue;
    if (e.fromModule === contract.module) continue;
    if (relaxed(manifest, contract, e)) continue;
    if (matchesAny(e.toFile, contract.public)) continue;
    out.push(finding(contract, {
      from: e.fromFile,
      to: e.toFile,
      message: `${e.toFile} is not part of ${contract.module}'s public surface`,
      edge: `${e.fromModule ?? 'unmapped'} -> ${e.toModule}`,
    }));
  }
  return out;
}

function fanOut(contract, graph, manifest) {
  const reach = new Map();
  for (const e of graph.edges) {
    if (!e.toModule || e.fromModule === e.toModule) continue;
    if (relaxed(manifest, contract, e)) continue;
    const key = contract.scope === 'module' ? e.fromModule : e.fromFile;
    if (!key) continue;
    if (!reach.has(key)) reach.set(key, new Set());
    reach.get(key).add(e.toModule);
  }

  const out = [];
  for (const [key, mods] of reach) {
    if (mods.size <= contract.max_modules) continue;
    out.push(finding(contract, {
      from: key,
      to: null,
      message: `reaches ${mods.size} modules (limit ${contract.max_modules}): ${[...mods].sort().join(', ')}`,
      edge: `${key} -> ${mods.size} modules`,
    }));
  }
  return out.sort((a, b) => a.from.localeCompare(b.from));
}

const EVALUATORS = { layers, forbidden, independence, boundary, 'fan-out': fanOut };

export function evaluate(manifest, graph) {
  const findings = [];
  const skipped = [];
  for (const contract of manifest.contracts) {
    const run = EVALUATORS[contract.type];
    if (!run) {
      skipped.push({ id: contract.id, type: contract.type, why: 'needs a type checker, not the import graph' });
      continue;
    }
    findings.push(...run(contract, graph, manifest));
  }
  return { findings, skipped };
}

export { REMEDY, POLICY };
