// @generated by archmap 0.1.2 — vendored copy, do not edit
// cm:guard globToRe is the whole mapping layer — a file the globs miss belongs to no module and is
//   invisible to every contract, so widening a glob silently narrows enforcement. `arch check`
//   reports unmapped coverage on every run for exactly this reason.
const CACHE = new Map();

export function globToRe(glob) {
  const hit = CACHE.get(glob);
  if (hit) return hit;

  let re = '';
  for (let i = 0; i < glob.length; i++) {
    const c = glob[i];
    if (c === '*') {
      if (glob[i + 1] === '*') {
        const slashAfter = glob[i + 2] === '/';
        re += slashAfter ? '(?:.*/)?' : '.*';
        i += slashAfter ? 2 : 1;
      } else {
        re += '[^/]*';
      }
    } else if (c === '?') {
      re += '[^/]';
    } else if (c === '{') {
      const end = glob.indexOf('}', i);
      if (end === -1) {
        re += '\\{';
      } else {
        re += `(?:${glob.slice(i + 1, end).split(',').map(escape).join('|')})`;
        i = end;
      }
    } else {
      re += escape(c);
    }
  }
  const compiled = new RegExp(`^${re}$`);
  CACHE.set(glob, compiled);
  return compiled;
}

function escape(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export function matchesAny(path, globs) {
  return globs.some((g) => globToRe(g).test(path));
}

/**
 * Assigns each file to at most one module. Later-declared modules win a tie, so a manifest can
 * carve a specific path out of a broader one by declaring it afterwards.
 */
export function buildMapper(manifest) {
  const entries = Object.entries(manifest.modules);
  const testGlobs = manifest.tests.globs;
  const generatedGlobs = manifest.generated.globs;
  const excludeGlobs = manifest.exclude;

  return function classify(path) {
    if (matchesAny(path, excludeGlobs)) return { module: null, kind: 'excluded' };
    if (matchesAny(path, generatedGlobs)) return { module: null, kind: 'generated' };

    let module = null;
    for (const [name, globs] of entries) if (matchesAny(path, globs)) module = name;

    const isTest = matchesAny(path, testGlobs);
    if (module === null) return { module: null, kind: isTest ? 'test' : 'unmapped' };
    return { module, kind: isTest ? 'test' : 'source' };
  };
}
