// @generated by archmap 0.1.2 — vendored copy, do not edit
import { buildMapper } from './map.mjs';

/**
 * Folds one or more provider outputs into a single graph keyed by repo-relative path, with each
 * file assigned to at most one module.
 */
export function normalize(manifest, providerResults) {
  const classify = buildMapper(manifest);
  const files = new Map();
  const edges = [];
  const unresolvable = [];
  const dropped = { generated: 0, excluded: 0 };

  const note = (path) => {
    if (files.has(path)) return files.get(path);
    const info = classify(path);
    files.set(path, info);
    return info;
  };

  for (const r of providerResults) {
    if (!r.ok) continue;
    for (const f of r.files) note(f);
    for (const u of r.unresolvable) {
      const info = note(u.from);
      if (info.kind === 'generated' || info.kind === 'excluded') continue;
      unresolvable.push({ ...u, module: info.module, language: r.language });
    }
    for (const e of r.edges) {
      const from = note(e.from);
      const to = note(e.to);
      if (from.kind === 'excluded' || to.kind === 'excluded') { dropped.excluded++; continue; }
      if (from.kind === 'generated' || to.kind === 'generated') { dropped.generated++; continue; }
      edges.push({
        fromFile: e.from,
        toFile: e.to,
        fromModule: from.module,
        toModule: to.module,
        fromKind: from.kind,
        toKind: to.kind,
        dynamic: Boolean(e.dynamic),
        language: r.language,
      });
    }
  }

  return { files, edges, unresolvable, dropped, coverage: coverageOf(files) };
}

function coverageOf(files) {
  const c = { total: 0, source: 0, test: 0, unmapped: 0, generated: 0, excluded: 0 };
  for (const { kind } of files.values()) {
    c.total++;
    c[kind]++;
  }
  const considered = c.source + c.test + c.unmapped;
  c.mappedPct = considered === 0 ? 0 : Math.round(((c.source + c.test) / considered) * 1000) / 10;
  return c;
}

/**
 * Module-level adjacency with transitive closure. `independence` needs the closure — the common
 * real violation is two features glued together through a shared module neither one names.
 */
export function moduleClosure(graph) {
  const direct = new Map();
  for (const e of graph.edges) {
    if (!e.fromModule || !e.toModule || e.fromModule === e.toModule) continue;
    if (!direct.has(e.fromModule)) direct.set(e.fromModule, new Set());
    direct.get(e.fromModule).add(e.toModule);
  }

  const closure = new Map();
  for (const start of direct.keys()) {
    const seen = new Set();
    const stack = [...(direct.get(start) ?? [])];
    while (stack.length) {
      const m = stack.pop();
      if (seen.has(m)) continue;
      seen.add(m);
      for (const next of direct.get(m) ?? []) if (!seen.has(next)) stack.push(next);
    }
    closure.set(start, seen);
  }
  return { direct, closure };
}

/**
 * One witness path from `a` to `b`, so a transitive finding can name the hop that caused it
 * instead of asserting a relationship the reader has to go and discover.
 */
export function witness(direct, a, b) {
  const prev = new Map([[a, null]]);
  const queue = [a];
  while (queue.length) {
    const cur = queue.shift();
    for (const next of direct.get(cur) ?? []) {
      if (prev.has(next)) continue;
      prev.set(next, cur);
      if (next === b) {
        const path = [b];
        for (let n = cur; n !== null; n = prev.get(n)) path.unshift(n);
        return path;
      }
      queue.push(next);
    }
  }
  return null;
}
